### ISSUE TITLE
Domain classifiers

### ISSUE THREAD

**Issue by samanehAb** [a514514772/DISE-Domain-Invariant-Structure-Extraction#2]
Hi,

First of all, thanks for sharing your codes.
Secondly, I am wondering why there are two domain classifiers in the codes each optimized separately (dclf1 and dclf2). The domain classifier is T in Figure 2. Right? As far as I understood  the pixel level classification (T) is only applied for comparison to the label ground truth of source domain and there is only one classifier. Am I right? I appreciate it if you guide me about it.

Best Regards,
Samane

**Comment by hui-po-wang** [comment]
Hi,

We build up our model on the basis of Tsai et al [24], which is also the major baseline in the experiment section. Following their idea, we use two-level domain classifiers. You might want to take a look at it.

Thanks

**Comment by samanehAb** [comment]
I will check it. Thanks for your advice.
