### ISSUE TITLE
Translation Texture Loss is missing

### ISSUE THREAD

**Issue by subeeshvasu** [a514514772/DISE-Domain-Invariant-Structure-Extraction#7]
Hi,

Thanks for sharing your codes.

As per the paper a "Translation Texture Loss" was employed to maintain the texture similarity between the translated images and target images. I couldn't find the use of "Translation Texture Loss" in your code. Can you please comment on it.

Best Regards,
Subeesh.

**Comment by hui-po-wang** [comment]
Hi,

We wrap both structure and texture losses into a single loss function for translation images. You may like to take a look at https://github.com/a514514772/DISE-Domain-Invariant-Structure-Extraction/blob/master/util/loss.py#L37.

Thanks.
Hui-Po

**Comment by subeeshvasu** [comment]
Hi,

Got it. Thanks a lot.

Cheers.
